server:
  port: 8082

spring:
  application:
    name: greeting

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.100.191.229:8081/eureka/
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

security:
  oauth2:
    resource:
      user-info-uri: http://47.100.191.229:8084/user

logging:
  level:
    org.springframework.security: DEBUG
