server:
  port: 8083

spring:
  application:
    name: rainbow
  datasource:
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.191.229:3306/rainbow?serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.100.191.229:8081/eureka/
  instance:
    prefer-ip-address: true
