server:
  port: 80

spring:
  application:
    name: gateway

zuul:
  routes:
    greeting:
      service-id: greeting
      path: /greeting/**
    rainbow:
      service-id: rainbow
      path: /rainbow/**
    auth:
      service-id: auth
      path: /auth/**
    frontend:
      service-id: frontend
      path: /**
  sensitive-headers: Cookie, Set-Cookie

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.100.191.229:8081/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
