server:
  port: 80

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: auth
        uri: lb://auth
        predicates:
        - Path=/auth/**
        filters:
        - StripPrefix=1
      - id: greeting
        uri: lb://greeting
        predicates:
        - Path=/greeting/**
        filters:
        - StripPrefix=1
  redis:
    host: 47.100.191.229

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.100.191.229:8081/eureka/
  instance:
    prefer-ip-address: true
